name: Build pGina

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet packages
      run: |
        nuget restore pGina\src\pGina-3.x.sln

    - name: Build Solution with MSBuild
      run: |
        msbuild pGinaBuild.msbuild.xml /p:Configuration=Release /m /v:minimal

    - name: Install Inno Setup
      run: |
        choco install innosetup --no-progress -y

    - name: Build Windows Installer (.exe)
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Installer\installer.iss

    - name: Upload Windows Installer (.exe)
      uses: actions/upload-artifact@v4
      with:
        name: pGinaSetup-Installer
        path: Installer/Output/pGinaSetup-*.exe
        if-no-files-found: error

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pGina-Release-Binaries
        path: |
          pGina/src/bin/
          Plugins/Core/bin/
          Plugins/Contrib/bin/
        if-no-files-found: warn
